### ISSUE TITLE
Time to Install Gem in Rails

### ISSUE THREAD

**Issue by Ravenclaw968** [gverger/ruby-cbc#10]
Hey,

Is it supposed to take an abnormal amount of time to download the gem into a rails app?

Thanks!

**Comment by gverger** [comment]
Hello @Ravenclaw968 , yes it is supposed to do so. It requires to compile the native library cbc with this gem: [cbc-wrapper](https://github.com/gverger/cbc-wrapper).

Depending on your machine, it can take a long time.
