### ISSUE TITLE
how do you express inequality?

### ISSUE THREAD

**Issue by nurettin** [gverger/ruby-cbc#16]
Hi,

model.enforce(a != b) # outputs "Not a constraint: false"

So how do you express "doesn't equal" (≠) with this library?

**Comment by gverger** [comment]
Hello,

ruby-cbc is using Cbc, which is an Integer Linear Programming solver. You cannot directly express ≠ with it, as it would make the problem not linear anymore.

https://math.stackexchange.com/questions/37075/how-can-not-equals-be-expressed-as-an-inequality-for-a-linear-programming-model

If you have (0-1) variables, you can express it like `1 - a == b`. If not you will need to be creative about how to express it in your context.

**Comment by nurettin** [comment]
Well I thought about it, you're right, I can use each possible number as a 0-1 bit and only one of the bits can be 1. That will take some memory but at least it can be expressed in terms of Cbc
