### ISSUE TITLE
Ctrl+C broken after solve

### ISSUE THREAD

**Issue by jackc** [gverger/ruby-cbc#17]
Once `solve` is called Ctrl+C will not interrupt the program. I'm guessing it does something with a signal handler or mask and never resets it.

```ruby
require 'ruby-cbc'

m = Cbc::Model.new
x1, x2, x3 = m.int_var_array(3, 0..Cbc::INF)
m.maximize(10*x1 + 6*x2 + 4*x3)
m.enforce(x1 + x2 + x3 <= 100)

m.to_problem.solve # comment this line out and Ctrl+C will work

puts "Press Ctrl+C to quit"

# Ctrl+C doesn't work here if we ran solve -- need to use Ctrl+\ to kill

sleep 9999
```

**Comment by gverger** [comment]
Hello, thanks for this issue, I fear it is from the underlying c library, and I have not been able to find a way to fix that for now.

I was thinking running it in a separate thread, but it won't run, as mentioned in https://github.com/gverger/ruby-cbc/issues/18.

**Comment by gverger** [comment]
Closing it, as I have no idea on how to deal with it.
If anyone wants to take a look and solve this, I'll gladly accept any PR.
