### ISSUE TITLE
Crash on OSX when run in web server

### ISSUE THREAD

**Issue by jackc** [gverger/ruby-cbc#18]
On OSX, if `solve` is called in a web request a `SystemStackError` in the C code will occur. This does not happen on Linux, and it does not happen if the `solve` call is outside of a web request.

I initially encountered this in Rails, but was able to produce a small test case with Sinatra. I tested with Ruby 2.5.1 and 2.4.4 without improvement. I also tried Webbrick, Puma, and Thin. No difference.

Sample (https://github.com/jackc/cbc-sinatra-crash):

```ruby
require 'sinatra'
require 'ruby-cbc'

def solve_it
  m = Cbc::Model.new
  x1, x2, x3 = m.int_var_array(3, 0..Cbc::INF)
  m.maximize(10*x1 + 6*x2 + 4*x3)
  m.enforce(x1 + x2 + x3 <= 100)
  m.to_problem.solve
end

solve_it
puts "Solve works outside of web server"

get '/' do
  solve_it
  "doesn't get here on Mac"
end
```
I ran into #17 while trying to diagnose this issue. Not sure if they're related.

Stack Trace:

```
jack@hk-47~/dev/ccsalespro/cbc-sinatra-crash$ bundle exec ruby main.rb
Solve works outside of web server
[2018-05-04 14:44:05] INFO  WEBrick 1.4.2
[2018-05-04 14:44:05] INFO  ruby 2.5.1 (2018-03-29) [x86_64-darwin17]
== Sinatra (v2.0.1) has taken the stage on 4567 for development with backup from WEBrick
[2018-05-04 14:44:05] INFO  WEBrick::HTTPServer#start: pid=47244 port=4567
2018-05-04 14:44:10 - SystemStackError - stack level too deep:
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/ruby-cbc-0.3.17/lib/ruby-cbc/problem.rb:132:in `Cbc_solve'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/ruby-cbc-0.3.17/lib/ruby-cbc/problem.rb:132:in `solve'
	main.rb:9:in `solve_it'
	main.rb:16:in `block in <main>'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/sinatra-2.0.1/lib/sinatra/base.rb:1634:in `call'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/sinatra-2.0.1/lib/sinatra/base.rb:1634:in `block in compile!'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/sinatra-2.0.1/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/sinatra-2.0.1/lib/sinatra/base.rb:1011:in `route_eval'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/sinatra-2.0.1/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/sinatra-2.0.1/lib/sinatra/base.rb:1039:in `block in process_route'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/sinatra-2.0.1/lib/sinatra/base.rb:1037:in `catch'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/sinatra-2.0.1/lib/sinatra/base.rb:1037:in `process_route'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/sinatra-2.0.1/lib/sinatra/base.rb:990:in `block in route!'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/sinatra-2.0.1/lib/sinatra/base.rb:989:in `each'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/sinatra-2.0.1/lib/sinatra/base.rb:989:in `route!'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/sinatra-2.0.1/lib/sinatra/base.rb:1096:in `block in dispatch!'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/sinatra-2.0.1/lib/sinatra/base.rb:1093:in `dispatch!'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `block in call!'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `call!'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/sinatra-2.0.1/lib/sinatra/base.rb:913:in `call'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/rack-protection-2.0.1/lib/rack/protection/xss_header.rb:18:in `call'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/rack-protection-2.0.1/lib/rack/protection/path_traversal.rb:16:in `call'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/rack-protection-2.0.1/lib/rack/protection/json_csrf.rb:26:in `call'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/rack-protection-2.0.1/lib/rack/protection/base.rb:50:in `call'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/rack-protection-2.0.1/lib/rack/protection/base.rb:50:in `call'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/rack-protection-2.0.1/lib/rack/protection/frame_options.rb:31:in `call'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/logger.rb:15:in `call'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/common_logger.rb:33:in `call'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/sinatra-2.0.1/lib/sinatra/base.rb:231:in `call'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/sinatra-2.0.1/lib/sinatra/base.rb:224:in `call'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/method_override.rb:22:in `call'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/sinatra-2.0.1/lib/sinatra/show_exceptions.rb:22:in `call'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/sinatra-2.0.1/lib/sinatra/base.rb:194:in `call'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/sinatra-2.0.1/lib/sinatra/base.rb:1957:in `call'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `block in call'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/sinatra-2.0.1/lib/sinatra/base.rb:1728:in `synchronize'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `call'
	/Users/jack/.rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/handler/webrick.rb:86:in `service'
	/Users/jack/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/webrick/httpserver.rb:140:in `service'
	/Users/jack/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/webrick/httpserver.rb:96:in `run'
	/Users/jack/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/webrick/server.rb:307:in `block in start_thread'
127.0.0.1 - - [04/May/2018:14:44:10 CDT] "GET / HTTP/1.1" 500 138906
```

**Comment by jackc** [comment]
Another data point: running in a fresh Rails 5.2.0 app does not crash on Mac. So strictly speaking it isn't always when run in a web server.

This feels like something in the underlying C code :fearful: .

**Comment by gverger** [comment]
Hello, thank you very much for the detailed issue here!

I have been doing some tests and I cannot make it work from within a thread.
```ruby
require 'ruby-cbc'
m = Cbc::Model.new
m.int_var(1..2)
Thread.new { m.to_problem.solve }.join
#=> 
# #<Thread:0x00007f8c0949a7b8@(pry):25 run> terminated with exception (report_on_exception is true):
# Traceback (most recent call last):
#         2: from (pry):26:in `block in <main>'
#         1: from /Users/guillaume/git/ruby-cbc/lib/ruby-cbc/problem.rb:132:in `solve'
#  /Users/guillaume/git/ruby-cbc/lib/ruby-cbc/problem.rb:132:in `Cbc_solve': stack level too deep (SystemStackError)
```
My guess is that your web server is trying to run in a thread.

My feeling here is that it might be beyond my understanding to solve this...

Any idea/suggestion is more than welcome !

**Comment by jackc** [comment]
A thread as the causal issue seems plausible. Maybe it does something that requires running on the main thread. Could be related to the signal handling issue in #17.  Don't think that a single-threaded web server is an option for me though.

As an alternative I tried shelling out to the underlying cbc binary. The C library doesn't seem to be very robust. It frequently crashed when it didn't like the input I gave it.

Even though it seems to work fine on Linux, these crashes made me pretty nervous about running this in process in production. The errors might be MacOS specific or they might bugs that are present everywhere but are only presently manifesting on MacOS and might occur on Linux if the environment changed.

After a number of different experiments, I finally arrived on a pretty awful hack, but it works. In short, I create thread and a pipe just before calling `to_problem`. From that fresh thread I `fork`. `fork` only copies a single thread so that thread exists outside of the web server and is now the main thread of the new child process. The child process calls `to_problem` and `solve` and writes the results back via the pipe.

It solves the MacOS crash since it is running outside of whatever environment (thread or web server) that it conflicts with. And it gives me peace of mind that it can't corrupt my web server process on my production Linux environment since the actual call to the problematic C code happens in that child process.

As a bonus, it "solves" the Ctrl+C signal handling issue as well.

**Comment by jackc** [comment]
Sure. Here's the abbreviated class that encapsulates the problem solving. The object is initialized and various methods are called that apply constraints to the `Cbc::Model`. When all the constraints and goals are set then `estimate_activity` is called.

```ruby
class Estimator
  class UnsolvedError < StandardError; end
  class TimeLimitReachedError < UnsolvedError; end
  class ProvenInfeasibleError < UnsolvedError; end

  def initialize
    @model = Cbc::Model.new
  end

  #
  # Various methods that apply constraints to model and set the goal
  #


  # To summarize:
  # 1. Start a new thread
  # 2. Set up a pipe in binary mode for the child process
  # 3. Fork a process and do the calculation
  # 4. Write the results back the pipe to the parent process
  # 5. Read results back out of the Thread.
  def estimate_activity
    thr = Thread.new do
      rd, wr = IO.pipe
      rd.binmode
      wr.binmode

      if fork
        wr.close
        result_bytes = rd.read
        rd.close
        Process.wait

        results = Marshal.load(result_bytes)
        raise results if results.kind_of? StandardError
        results
      else
        rd.close

        results = begin
          estimate_activity_in_process
        rescue StandardError => e
          e
        end
        wr.write Marshal.dump(results)
        exit! # ensure no at_exit handlers run and break the server
      end
    end

    thr.value
  end

  def estimate_activity_in_process
    problem = model.to_problem
    problem.set_time_limit 10
    problem.solve

    raise TimeLimitReachedError if problem.time_limit_reached?
    raise ProvenInfeasibleError if problem.proven_infeasible?

    # Read results with problem.value_of into my own result structure and return
  end
end
```

Not sure how generally applicable this approach is. First, `fork` definitely excludes Windows. Second, the problem is not marshallable, so the solution has to be read out and translated into normal Ruby objects to be sent back to the parent process. Don't know what the general case of that would look like.

As far as performance, `fork` is pretty fast. The impact may be measurable, but it's not noticeable for my use case.

**Comment by gverger** [comment]
Thanks, this is a pretty clever way to isolate it.
It seems heavy compared to just calling `solve`, but as you are just trying to run it from a webserver, nothing crazy here, you will probably not be the only one with this issue.

I'll try to see how I could integrate this in the default behavior... It is not clear for me wether I will provide an option or it will be the normal behavior.

**Comment by gverger** [comment]
I have refactored a bit the `Problem` class to isolate calls to the native library.
I have been able to make the `fork` work, tests pass, but it is not enough in your little example: it still crashes with `marshall data too short` because the call to `Cbc_solve` fails.
Here is my working branch : https://github.com/gverger/ruby-cbc/compare/threads
The magic is in the `Problem#solve` method.

I have not been able to make it work with threads, and I am not sure I completely understand why we need threads here (I mean, threads + fork).
I also don't get why it is working in tests, but not in the case of the webserver (which is the same as just wrapping it into a thread).

The good news about this one is that it closes the other issue https://github.com/gverger/ruby-cbc/issues/17, but I didn't check we could still `Ctrl-C` *during* the native library call.

**Comment by jackc** [comment]
The reason for the new thread is to ensure that the forked process started with a blank slate as much as possible. `fork` only forks a single thread, so by starting a new thread and forking that we minimize the baggage that the new process carries with it from the original program. It definitely didn't work for me with `fork` alone.

As far as the marshal data too short error, handling errors from the actual calculation is why I rescue all errors from the in process execution and marshal them and send back to the parent process where they are re-raised.

**Comment by gverger** [comment]
Sorry, I don't have any clue on how I can solve this.

I will close the issue now, it has been around long enough.
Feel free to reopen it if you have any new thoughts on it.
