### ISSUE TITLE
Installation Notes

### ISSUE THREAD

**Issue by ankane** [gverger/ruby-cbc#22]
Hey @gverger, thanks for this great library! I wanted to share some notes about installation that can hopefully be incorporated into the readme.

I think this line is outdated with the release of cbc-wrapper 2.9.9.4.

> The gem includes a version of the Coin-Or Cbc library. If the system on which it is installed is not Linux 64bits, it downloads the library sources and recompiles them at installation.

On Ubuntu, users need to do:

```sh
sudo apt install coinor-libcbc-dev
```

On Heroku, I was able to get it working with the [Apt buildpack](https://github.com/heroku/heroku-buildpack-apt) with an `Aptfile` of:

```txt
coinor-libcbc-dev
```

And setting `LD_LIBRARY_PATH` so it can find LAPACK and BLAS.

```sh
heroku config:set LD_LIBRARY_PATH=/app/.apt/usr/lib/x86_64-linux-gnu/lapack:/app/.apt/usr/lib/x86_64-linux-gnu/blas 
```

The last part is needed due to [this issue](https://github.com/heroku/heroku-buildpack-apt/issues/35), or it'll fail at runtime with `liblapack.so.3: cannot open shared object file: No such file or directory - /app/vendor/bundle/ruby/2.6.0/gems/cbc-wrapper-2.9.9.4/ext/cbc-wrapper/cbc_wrapper.so`.

I also tried an older cbc-wrapper on Heroku without the Apt buildpack (`gem "cbc-wrapper", "2.9.9.3"`), and it installs, but fails at runtime with `libCgl.so.1: cannot open shared object file: No such file or directory - /app/vendor/bundle/ruby/2.6.0/gems/cbc-wrapper-2.9.9.3/ext/cbc-wrapper/cbc_wrapper.so (LoadError)`.

Hopefully this is helpful to other users.

**Comment by gverger** [comment]
Hello @ankane, thank you for the feedback, it seems very useful indeed :)

Do you want to open a PR with the change to the readme? I can do it myself too, no problem

**Comment by ankane** [comment]
Thanks @gverger, will defer to you to incorporate in whichever way you think is best.

**Comment by ankane** [comment]
Quick follow up: Mac users can now install CBC with `brew install cbc`.

**Comment by gverger** [comment]
Thanks @ankane I've updated the readme. Your feedback was precious

**Comment by ankane** [comment]
Thanks @gverger, looks great. Love how easy the gem is to use.
